apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: express-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: express-app
  endpoints:
    - port: "http-metrics" # <-- must match Service port name
      path: /metrics
      interval: 15s
